### ISSUE TITLE
set domain name as endpoint

### ISSUE THREAD

**Issue by poky1084** [shimberger/wg-http-proxy#1]
I would like to use a domain as endpoint for the wg config. if i set the env variable to a domain:port it gives me an error .
![Screenshot 2022-03-15 110715](https://user-images.githubusercontent.com/6255299/158346940-a1fca5c0-6465-4969-a5d3-9ef7bc0aa09a.png)

At this time I ping the domain and copy the ip and set it as  WG_ENDPOINT=...
It would be perfect to use a domain name as well.

**Comment by poky1084** [comment]
I see it is more likely `go118-netip` package problem.

**Comment by shimberger** [comment]
Thanks for the feedback. The wireguard package needs an IP and I was too lazy to add this extra feature. I can look at it though.

**Comment by poky1084** [comment]
I made some editing in the package files in sourcecode files and it is enough for my needs.

Edited file: `wg-http-proxy-main\vendor\golang.zx2c4.com\go118\netip\netip.go`

Modifications:
1. Added "net" in imports
```
import (
	"errors"
	"math"
	"strconv"
	"net"
	
	"golang.zx2c4.com/go118/netip/internal/bytealg"
	"golang.zx2c4.com/go118/netip/internal/itoa"
	"golang.zx2c4.com/go118/netip/internal/intern"
)
```
2. In `parseIPv4` function, At this line: `return Addr{}, parseAddrError{in: s, msg: "unexpected character", at: s[i:]}` uncomment then added some code to lookup the domain then return (rerun) the function with ip.
```
} else {
	ipstr, _ := net.ResolveIPAddr("ip4:icmp", s[i:])
	return parseIPv4(ipstr.String())
	// return Addr{}, parseAddrError{in: s, msg: "unexpected character", at: s[i:]}
}
```

These edits are just for my personal use. It worked

**Comment by poky1084** [comment]
failed with: `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID` error message in chrome on one website after the editings, i dont know how to fix, looking forward for you update on this domain ip resolving :) Reason i need this feature is I think the domain name could give out dynamic IPs time to time and i cant change manually every time the configs to other ip, im not too familiar with Wireguard so i'm not sure about this.
