### ISSUE TITLE
Mean of contacting you ?

### ISSUE THREAD

**Issue by fabcotech** [shimberger/wg-http-proxy#2]
Hello Sebastian 

You website does not work http://www.sebastian.himberger.de/ we're interesting in coding similar things as wg-http-proxy. And would like to exchange with you and ask few questions, is that possible ??

Thanks very much

ps: we are the dappy team (France), we build an alternative to DNS based on blockchain, cheers

**Comment by shimberger** [comment]
Hey,

I am on vacation this week. You can reach me at ***@***.*** I’m
happy to help. What kind of questions are you thinking about? The project
is more or less a little toy at this point.

Cheers from Berlin.
Sebastian
